name: Deploy to Azure

on:
  push:
    branches:
      - main  # Change this to match your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Make sure this matches your build script in package.json

    - name: Deploy to Azure Blob Storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.23.0
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      run: |
        az storage blob upload-batch --account-name <your-storage-account-name> --destination <container-name> --source build

  # Optionally, you might want to include steps for cleaning up previous deployments, notifying stakeholders, etc.
